### ISSUE TITLE
TypeError: LlamaCpp.stream() got an unexpected keyword argument 'input'

### ISSUE THREAD

**Issue by lasdem** [h2oai/h2ogpt#626]
After Updating from f3a34b6 to 4324ae5 I get the following error when submitting a query to the chat: 
```python
thread exception: (<class 'TypeError'>, TypeError("LlamaCpp.stream() got an unexpected keyword argument 'input'"), <traceback object at 0x7f206e7fea00>)
make stop: (<class 'TypeError'>, TypeError("LlamaCpp.stream() got an unexpected keyword argument 'input'"), <traceback object at 0x7f206e7fea00>)
Traceback (most recent call last):
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/lasdem/gpt/h2ogpt/src/gradio_runner.py", line 1763, in bot
    for res in get_response(fun1, history):
  File "/home/lasdem/gpt/h2ogpt/src/gradio_runner.py", line 1714, in get_response
    for output_fun in fun1():
  File "/home/lasdem/gpt/h2ogpt/src/gen.py", line 1810, in evaluate
    for r in run_qa_db(
  File "/home/lasdem/gpt/h2ogpt/src/gpt_langchain.py", line 2490, in _run_qa_db
    raise thread.exc
  File "/home/lasdem/gpt/h2ogpt/src/gpt_langchain.py", line 2479, in _run_qa_db
    thread.join()
  File "/home/lasdem/gpt/h2ogpt/src/utils.py", line 407, in join
    raise self.exc
  File "/home/lasdem/gpt/h2ogpt/src/utils.py", line 388, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 106, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 165, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/llms/base.py", line 186, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/llms/base.py", line 279, in generate
    output = self._generate_helper(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/llms/base.py", line 223, in _generate_helper
    raise e
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/llms/base.py", line 210, in _generate_helper
    self._generate(
  File "/home/lasdem/mambaforge/envs/h2ogpt/lib/python3.10/site-packages/langchain/llms/base.py", line 602, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/lasdem/gpt/h2ogpt/src/gpt4all_llm.py", line 333, in _call
    for token in self.stream(input=prompt, stop=stop):
TypeError: LlamaCpp.stream() got an unexpected keyword argument 'input'
```

I am running with the following command prompt using CPU (no GPU): 
`python generate.py --base_model='llama' --prompt_type=llama2 --user_path=user_path`

**Comment by lasdem** [comment]
OK Solved it by updating my libraries with:
```sh
pip install -r requirements.txt
pip install -r reqs_optional/requirements_optional_langchain.txt
```
